[package]
name = "clusterzip"
version = "0.1.0"
authors = ["kahlo <kahlo.phoenix@gmail.com>"]

[dependencies]
volatile_cell = "1.0.0"
monitor = "0.1.0"
num_cpus = "1.0"
rand = "0.4"
time = "0.1"
stopwatch = "0.0.7"
tokio = "0.1.4"
serde = "1.0.35"
local-ip = "0.1.0"
ssh2 = "0.3"
file = "1.1.1"
