[package]
name = "clusterzip"
version = "0.1.0"
authors = ["kahlo <kahlo.phoenix@gmail.com>"]

[dependencies]
volatile_cell = "1.0.0"
monitor = "0.1.0"
num_cpus = "1.0"
rand = "0.4"
time = "0.1"
stopwatch = "0.0.7"
